---
label: Hugo Config
hide_body: true
fields:
- type: text
  name: title
  label: Title
- type: text
  name: baseURL
  label: Base URL
- type: text
  name: languageCode
  label: Language Code
  description: Language Code for this site
- type: field_group
  name: params
  fields:
  - name: show_bugo
    type: boolean
    label: Show Bugo some love.
    description: Put the word out about Bugo.
    default: true
  - type: text
    name: title
    description: Give your website a title for social media.
    label: Open Graph Title
  - type: text
    name: description
    label: Open Graph Description
    description: Give a short description of your website for social media.
  - type: list
    name: images
    label: Open Graph Images
    description: Default images for social media
  - type: text
    name: google_cloud_api
    label: Google Cloud API
    description: If you plan to use any Google Cloud Products in your templates.
  - type: field_group
    name: theme_colors
    fields:
    - name: primary
      type: color
      label: Primary
      config:
        required: false
        color_format: Hex
    - name: secondary
      type: color
      label: Secondary
      config:
        required: false
        color_format: Hex
    - name: accent_1
      type: color
      label: Accent 1
      config:
        required: false
        color_format: Hex
    - name: accent_2
      type: color
      label: Accent 2
      config:
        required: false
        color_format: Hex
    - name: light
      type: color
      label: Light
      config:
        required: false
        color_format: Hex
    - name: dark
      type: color
      label: Dark
      config:
        required: false
        color_format: Hex
    - name: white
      type: color
      label: White
      config:
        required: false
        color_format: Hex
    - name: black
      type: color
      label: Black
      config:
        required: false
        color_format: Hex
    - name: info
      type: color
      label: Info
      config:
        required: false
        color_format: Hex
    - name: success
      type: color
      label: Success
      config:
        required: false
        color_format: Hex
    - name: warning
      type: color
      label: Warning
      config:
        required: false
        color_format: Hex
    - name: danger
      type: color
      label: Danger
      config:
        required: false
        color_format: Hex
    label: Theme Colors
    description: Add colors for use with your website
  - type: field_group
    name: breakpoints
    fields:
    - type: field_group
      name: xs
      label: Extra Small Breakpoint
      fields:
      - type: text
        name: bp
        label: Breakpoint Width
        config:
          required: true
        description: 'Where does this breakpoint start? use: auto | value | initial
          | inherit'
        default: 0px
      - type: text
        name: mw
        label: Maximum Width
        description: 'The container''s maximum width.  use: none | length | initial
          | inherit'
      - type: text
        name: base
        label: Base Font Size
        description: 'The base font size at this breakpoint. Use: length only;'
      - type: number
        name: ratio
        label: Modular Scale Ratio
        description: Ratio used to scale the site at this breakpoint. Use +/- integer.
          The base to the scale is 0.
    - type: field_group
      name: sm
      label: Small Breakpoint
      fields:
      - type: text
        name: bp
        label: Breakpoint Width
        config:
          required: true
        description: 'Where does this breakpoint start? use: auto | value | initial
          | inherit'
        default: 0px
      - type: text
        name: mw
        label: Maximum Width
        description: 'The container''s maximum width.  use: none | length | initial
          | inherit'
      - type: text
        name: base
        label: Base Font Size
        description: 'The base font size at this breakpoint. Use: length only;'
      - type: number
        name: ratio
        label: Modular Scale Ratio
        description: Ratio used to scale the site at this breakpoint. Use +/- integer.
          The base to the scale is 0.
    - type: field_group
      name: md
      label: Medium Breakpoint
      fields:
      - type: text
        name: bp
        label: Breakpoint Width
        config:
          required: true
        description: 'Where does this breakpoint start? use: auto | value | initial
          | inherit'
        default: 0px
      - type: text
        name: mw
        label: Maximum Width
        description: 'The container''s maximum width.  use: none | length | initial
          | inherit'
      - type: text
        name: base
        label: Base Font Size
        description: 'The base font size at this breakpoint. Use: length only;'
      - type: number
        name: ratio
        label: Modular Scale Ratio
        description: Ratio used to scale the site at this breakpoint. Use +/- integer.
          The base to the scale is 0.
    - type: field_group
      name: lg
      label: Large Breakpoint
      fields:
      - type: text
        name: bp
        label: Breakpoint Width
        config:
          required: true
        description: 'Where does this breakpoint start? use: auto | value | initial
          | inherit'
        default: 0px
      - type: text
        name: mw
        label: Maximum Width
        description: 'The container''s maximum width.  use: none | length | initial
          | inherit'
      - type: text
        name: base
        label: Base Font Size
        description: 'The base font size at this breakpoint. Use: length only;'
      - type: number
        name: ratio
        label: Modular Scale Ratio
        description: Ratio used to scale the site at this breakpoint. Use +/- integer.
          The base to the scale is 0.
    - type: field_group
      name: xl
      label: X-Large Breakpoint
      fields:
      - type: text
        name: bp
        label: Breakpoint Width
        config:
          required: true
        description: 'Where does this breakpoint start? use: auto | value | initial
          | inherit'
        default: 0px
      - type: text
        name: mw
        label: Maximum Width
        description: 'The container''s maximum width.  use: none | length | initial
          | inherit'
      - type: text
        name: base
        label: Base Font Size
        description: 'The base font size at this breakpoint. Use: length only;'
      - type: number
        name: ratio
        label: Modular Scale Ratio
        description: Ratio used to scale the site at this breakpoint. Use +/- integer.
          The base to the scale is 0.
    - type: field_group
      name: xxl
      label: XX-Large Breakpoint
      fields:
      - type: text
        name: bp
        label: Breakpoint Width
        config:
          required: true
        description: 'Where does this breakpoint start? use: auto | value | initial
          | inherit'
        default: 0px
      - type: text
        name: mw
        label: Maximum Width
        description: 'The container''s maximum width.  use: none | length | initial
          | inherit'
      - type: text
        name: base
        label: Base Font Size
        description: 'The base font size at this breakpoint. Use: length only;'
      - type: number
        name: ratio
        label: Modular Scale Ratio
        description: Ratio used to scale the site at this breakpoint. Use +/- integer.
          The base to the scale is 0.
    - type: field_group
      name: xxxl
      label: XXX-Large Breakpoint
      fields:
      - type: text
        name: bp
        label: Breakpoint Width
        config:
          required: true
        description: 'Where does this breakpoint start? use: auto | value | initial
          | inherit'
        default: 0px
      - type: text
        name: mw
        label: Maximum Width
        description: 'The container''s maximum width.  use: none | length | initial
          | inherit'
      - type: text
        name: base
        label: Base Font Size
        description: 'The base font size at this breakpoint. Use: length only;'
      - type: number
        name: ratio
        label: Modular Scale Ratio
        description: Ratio used to scale the site at this breakpoint. Use +/- integer.
          The base to the scale is 0.
    label: Front End Breakpoints
    description: Customize your site's responsive features.
  - type: field_group
    name: sidebar_widgets
    label: Sidebar Widgets
    fields:
    - type: blocks
      name: widgets
      label: Widgets
      template_types:
      - widget-search-form
      - widget-markdown
      - widget-categories
      - widget-menu
      - widget-latest-posts
      - widget-related-posts
  - name: google_fonts
    type: field_group
    config: {}
    fields:
    - name: import_fonts
      type: list
      config:
        use_select: false
        min: 
        max: 
      label: Import Fonts
      description: Add the names of the fonts with weights you want to import
    - name: base_font
      type: text
      config:
        required: false
      label: Base Font
      description: Add a base font from Google Fonts or Adobe TypeKit
      default: Roboto
    - name: heading_font
      type: text
      config:
        required: false
      label: Heading Font
      description: Add a base font from Google Fonts or Adobe TypeKit
      default: Roboto
    label: Google Fonts
    description: Customize the fonts used on this site.
  description: Customize your site
  label: Bugo Parameters
- name: sectionPagesMenu
  type: select
  default: []
  config:
    required: false
    options:
    - main
    - secondary
    - mobile
    - privacy
    source:
      type: simple
      section: 
      file: 
      path: 
  label: Section Menu
  description: Site sections will get automatically added to this menu.
- name: summaryLength
  type: number
  label: Summary Length
  default: '25'
  config:
    min: '25'
    max: '200'
    step: 
  description: How many words to show in a page/post summary.
- name: paginate
  type: number
  label: Paginatation
  description: Enter the number of posts you want to display when showing them in
    a list.
  default: '10'
  config:
    min: 
    max: 
    step: 
- type: text
  name: googleAnalytics
  label: Google Analytics ID
  description: Enter your Google Analytics ID in to start tracking. Tracking only
    takes place in production environments.
- type: field_group
  name: menu
  label: menu
  fields:
  - type: list
    name: main
    label: main
  - type: list
    name: secondary
    label: secondary
  - type: list
    name: footer
    label: footer
  - type: list
    name: privacy
    label: privacy
pages:
- config.yaml
