---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: document
  path: content/_index.md
  label: temp
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: content/sample-pages
  label: Sample pages
  create: all
  match: "**/*"
- type: directory
  path: content/posts
  label: News
  create: all
  match: "**/*"
  templates:
  - b-template-post
  - b-template-list-page
- type: directory
  path: content/installation
  label: Installation & Config Docs
  create: all
  match: "**/*"
  templates:
  - b-template-page
- type: directory
  path: content/templates
  label: Template Documentation
  create: all
  match: "**/*"
  new_doc_ext: md
  templates:
  - b-template-page
- type: heading
  label: Config Options
- type: document
  path: data/categories.yaml
  label: Categories
- type: document
  path: data/organization.yaml
  label: Organization
- type: document
  path: config.yaml
  label: Site Config
- type: document
  path: data/styles.yaml
  label: Site Styles
- type: document
  path: data/config.yaml
  label: Widgets
- type: heading
  label: Documentation
- type: directory
  path: themes
  label: Theme Docs
  create: none
  match: "**/*.md"
  exclude: "{**/archetypes,**/_forestry}"
  templates:
  - blank
upload_dir: ''
public_path: https://res.cloudinary.com/bugo/image/upload
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_command: hugo -E -F -D -b $DEPLOY_URL -d public
  publish_command: hugo -d public
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.55.6
  publish_env:
  - HUGO_ENV=production
  - HUGO_VERSION=0.55.6
  preview_output_directory: public
  output_directory: public
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
version: 0.55.6
