---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: content/posts
  label: Posts
  create: documents
  match: "**/*"
  templates:
  - b-template-post
- type: heading
  label: Config Options
- type: document
  path: data/categories.yaml
  label: Categories
- type: document
  path: data/organization.yaml
  label: Organization
- type: document
  path: config.yaml
  label: Site Config
- type: document
  path: data/config.yaml
  label: Widgets
upload_dir: ''
public_path: https://res.cloudinary.com/lasershootingtrainer/image/upload
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.55.6
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.57.2
